available: 4
zones:
   - number: 1
     name: 'Front Lawn, Left'
     delay_trigger: WeMo Motion
     schedule:
      sunday:
        - time: '0600'
          duration: 30
        - time: '2100'
          duration: 30
      monday:
        - time: '0600'
          duration: 30
   - number: 2
     name: 'Front Lawn, Right'
     schedule:
        sunday:
          - time: '0600'
            duration: 30
          - time: '2100'
            duration: 30
        monday:
          - time: '0600'
            duration: 30
   - number: 3
     name: 'Back Lawn, Left'
     delay_trigger: WeMo Motion
     schedule:
      sunday:
        - time: '0600'
          duration: 30
        - time: '2100'
          duration: 30
      monday:
        - time: '0600'
          duration: 30
   - number: 4
     name: 'Back Lawn, Right'
     schedule:
        sunday:
          - time: '0600'
            duration: 30
          - time: '2100'
            duration: 30
        monday:
          - time: '0600'
            duration: 30
